[]
args.client_id_list = None
training_type != FEDML_TRAINING_PLATFORM_CROSS_DEVICE and training_type != FEDML_TRAINING_PLATFORM_CROSS_SILO
bsize is 128
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:09:56] [INFO] [__init__.py:109:print_args] ==== args = {'yaml_config_file': '/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/config.yml', 'run_id': '0', 'rank': 0, 'local_rank': 0, 'node_rank': 0, 'role': 'client', 'central_training': 0, 'yaml_paths': ['/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/config.yml'], 'training_type': 'simulation', 'random_seed': 0, 'dataset': 'ICU', 'data_cache_dir': '/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/eICU_Data/', 'partition_method': 'hetero', 'partition_alpha': 0.5, 'model': 'GRU', 'input_dim': 128, 'hidden_dim': 32, 'num_layers': 2, 'output_dim': 1, 'dropout_prob': 0.05, 'dist_model_dir': '/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/', 'central_model_dir': '/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/central_training/', 'federated_optimizer': 'FedAvg', 'client_id_list': '[]', 'client_num_in_total': 5, 'client_num_per_round': 3, 'comm_round': 5, 'epochs': 2, 'batch_size': 128, 'client_optimizer': 'adamw', 'learning_rate': 0.005, 'weight_decay': 0.005, 'recruitment': False, 'central_epochs': 15, 'frequency_of_the_test': 1, 'using_gpu': False, 'gpu_id': 0, 'backend': 'sp', 'log_file_dir': '/Users/vscheltjens/fedml-server/fedml/logs', 'enable_wandb': True, 'wandb_key': '8d579c56c0eda8929353aac11d399b96e5aa9e71', 'wandb_entity': 'vs-health', 'wandb_project': 'federated_gru_eicu', 'central_wandb_project': 'recr_central_training', 'worker_num': 3, 'sys_perf_profiling': True, 'config_version': 'release', 'current_running_dir': '/Users/vscheltjens/fedml-client', 'os_name': 'MacOS', 'version': 'release', 'device_id': '0xC02F52N9MD6R', 'cloud_region': '', 'mqtt_config_path': '', 's3_config_path': '', 'log_server_url': 'https://open.fedml.ai/fedmlLogsServer/logs/update'}
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:09:56] [INFO] [ml_engine_adapter.py:147:get_torch_device] args = <fedml.arguments.Arguments object at 0x7fafe8190f70>, using_gpu = False, device_id = 0, device_type = cpu
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:09:56] [INFO] [device.py:48:get_device] device = cpu
Loaded Global dataloaders
24698 24698
covered hospital 0
covered hospital 1
covered hospital 2
covered hospital 3
covered hospital 4
reached target point: model and data loaded -----> start training federated
120
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [INFO] [fedavg_api.py:43:__init__] model = GRUModel(
  (gru): GRU(128, 32, num_layers=2, batch_first=True, dropout=0.05)
  (fc): Linear(in_features=32, out_features=1, bias=True)
  (gru_dropout): Dropout(p=0.05, inplace=False)
  (batch_norm): BatchNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (instance_norm): InstanceNorm1d(1, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
  (relu): ReLU()
)
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [INFO] [fedavg_api.py:46:__init__] self.model_trainer = <fedml.ml.trainer.icu_trainer.ModelTrainerICU object at 0x7fafa8c78760>
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [INFO] [fedavg_api.py:55:_setup_clients] ############setup_clients (START)#############
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [INFO] [fedavg_api.py:67:_setup_clients] ############setup_clients (END)#############
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [INFO] [fedavg_api.py:70:train] self.model_trainer = <fedml.ml.trainer.icu_trainer.ModelTrainerICU object at 0x7fafa8c78760>
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [INFO] [fedavg_api.py:77:train] ################Communication round : 0
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [INFO] [fedavg_api.py:142:_client_sampling] client_indexes = [2 0 1]
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [INFO] [fedavg_api.py:88:train] client_indexes = [2 0 1]
[FedML-Server(0) @device-id-0] [Sun, 15 Jan 2023 17:10:32] [ERROR] [mlops_runtime_log.py:34:handle_exception] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/distributed_training/federated.py", line 24, in <module>
    simulator.run()
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/fedml/runner.py", line 123, in run
    self.runner.run()
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/fedml/simulation/simulator.py", line 67, in run
    self.fl_trainer.train()
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/fedml/simulation/sp/fedavg/fedavg_api.py", line 102, in train
    w = client.train(copy.deepcopy(w_global))
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/fedml/simulation/sp/fedavg/client.py", line 26, in train
    self.model_trainer.train(self.local_training_data, self.device, self.args)
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/fedml/ml/trainer/icu_trainer.py", line 60, in train
    outputs = model(inputs.float())
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/vscheltjens/Documents/PhD/Projects/eicu-cl-req/model/model.py", line 42, in forward
    out = self.instance_norm(out)
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/torch/nn/modules/instancenorm.py", line 72, in forward
    return self._handle_no_batch_input(input)
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/torch/nn/modules/instancenorm.py", line 31, in _handle_no_batch_input
    return self._apply_instance_norm(input.unsqueeze(0)).squeeze(0)
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/torch/nn/modules/instancenorm.py", line 34, in _apply_instance_norm
    return F.instance_norm(
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/torch/nn/functional.py", line 2494, in instance_norm
    _verify_spatial_size(input.size())
  File "/usr/local/Caskroom/miniconda/base/envs/fed-cl-req-dev/lib/python3.10/site-packages/torch/nn/functional.py", line 2461, in _verify_spatial_size
    raise ValueError("Expected more than 1 spatial element when training, got input size {}".format(size))
ValueError: Expected more than 1 spatial element when training, got input size torch.Size([1, 120, 1])